obj-$(CONFIG_TBS_PCIE_DVB) += tbs_pcie-dvb.o
tbs_pcie-dvb-objs += tbs_pcie.o

EXTRA_CFLAGS += -Idrivers/media/dvb-core/
EXTRA_CFLAGS += -Idrivers/media/dvb-frontends/
EXTRA_CFLAGS += -Idrivers/media/tuners/
